spring: 
    jpa: 
        hibernate: 
            ddl-auto: update 
    datasource: 
        url: jdbc:mariadb://localhost:3306/shoppingmall?useUnicode=true&characterEncoding=utf-8 
        username: root
        password: jR9903622
        driver-class-name: org.mariadb.jdbc.Driver